# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Dispatch' do
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
end

target 'DispatchTests' do
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
end

